version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/vectorstore:/app/app/vectorstore
    env_file:
      - .env
    restart: always

volumes:
  chroma_data:
